# Generated by Django 2.0 on 2018-05-30 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MovieInfo',
            fields=[
                ('index', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('image', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=50)),
                ('actor', models.CharField(max_length=100)),
                ('time', models.CharField(max_length=50)),
                ('score', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Recommended',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.CharField(max_length=10)),
                ('index', models.CharField(max_length=5)),
                ('recommended', models.CharField(max_length=50)),
            ],
        ),
    ]
